---
# Ansible Galaxy requirements
# Install with: ansible-galaxy install -r requirements.yaml

collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=8.0.0"
  - name: kubernetes.core
    version: ">=2.4.0"
